#!/usr/bin/env bash

here=$(perl -e 'use File::Basename; use Cwd "abs_path"; print dirname(abs_path(@ARGV[0]));' -- "$0")

errored=false

# install Homebrew base system
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || errored=true

# taps
while read -r tap; do
    [[ $tap == \#* ]] && continue # skip comments
    echo "${BOLD}${BLUE}brew tap $tap${RESET}" >&2
    brew tap $tap || errored=true
    { echo; echo; echo; } >&2
done < "$here/taps"

# some formulae depend on x11, so install brew-cask and xquartz first
echo "${BOLD}${BLUE}brew install brew-cask${RESET}" >&2
brew install brew-cask
{ echo; echo; echo; } >&2
echo "${BOLD}${BLUE}brew cask install xquartz${RESET}" >&2
brew cask install xquartz
{ echo; echo; echo; } >&2

# formulae
while read -r optstring; do
    [[ $optstring == \#* ]] && continue # skip comments
    echo "${BOLD}${BLUE}brew install $optstring${RESET}" >&2
    brew install $optstring || errored=true
    { echo; echo; echo; } >&2
done < "$here/formulae"

# specials
"$here/special" || errored=true

[[ $errored == false ]]
