#!/usr/bin/env zsh

### link apps
print -P "%B%F{blue}brew linkapps emacs%f%b" >&2
brew linkapps emacs
print -P "%B%F{blue}brew linkapps mpv%f%b" >&2
brew linkapps mpv
print -P "%B%F{blue}brew linkapps terminal-notifier%f%b" >&2
brew linkapps terminal-notifier

### keg-only
print -P "%B%F{blue}mkdir -p ~/dev/bin%f%b" >&2
mkdir -p ~/dev/bin
# curl
curl_bin="$(brew --prefix curl)/bin"
print -P "%B%F{blue}ln -sf '$curl_bin'/* ~/dev/bin%f%b" >&2
ln -sf $curl_bin/* ~/dev/bin
# gnu-getopt
gnu_getopt_bin="$(brew --prefix gnu-getopt)/bin"
print -P "%B%F{blue}ln -sf '$gnu_getopt_bin'/* ~/dev/bin%f%b" >&2
ln -sf $gnu_getopt_bin/* ~/dev/bin

### permissions
# htop
htop="$(brew --prefix htop-osx)/bin/htop"
print -P "%B%F{blue}sudo chown root:wheel '$htop'%f%b" >&2
sudo chown root:wheel $htop
print -P "%B%F{blue}sudo chmod u+s '$htop'%f%b" >&2
sudo chmod u+s $htop

# mutt
mutt="$(brew --prefix mutt)/bin/mutt"
print -P "%B%F{blue}sudo chown root:mail '$mutt'%f%b" >&2
sudo chown root:mail $mutt
print -P "%B%F{blue}sudo chmod u+s '$mutt'%f%b" >&2
sudo chmod u+s $mutt
