#!/usr/bin/env zsh

# This scripts set up linuxbrew on Linux (additional distro dependent
# dependencies might need to be installed independently).
# https://github.com/Homebrew/linuxbrew

set +x
if [[ ! -e ~/.linuxbrew ]]; then
    git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew || { echo "${RED}error: git-clone failed${RESET}" >&2; exit 1; }
fi

# update environment to include linuxbrew paths
source ~/.config/env
