#!/usr/bin/env bash

errored=false

### move apps into /Applications
function find_and_move_app
{
    shopt -s nullglob
    paths=( /opt/homebrew-cask/Caskroom/"$1"/*/"$2" )
    [[ -n $paths ]] || { echo "${RED}error: no install found in /opt/homebrew-cask/Caskroom/$1${RESET}" >&2; return 1; }
    src=${paths[-1]}
    dst=/Applications/$3
    echo "${BOLD}${BLUE}rm -f '$dst'${RESET}" >&2
    rm -f "$dst" || { echo "${RED}error: '$dst' already exists${RESET}" >&2; return 1; }
    echo "${BOLD}${BLUE}mv '$src' '$dst'${RESET}" >&2
    mv "$src" "$dst" || { echo "${RED}error: failed to move into '$dst'${RESET}" >&2; return 1; }
    echo "${BOLD}${BLUE}ln -s '$dst' '$src'${RESET}" >&2
    ln -s "$dst" "$src"
}

# chromium
find_and_move_app "chromium" "chrome-mac/Chromium.app" "Chromium.app" || errored=true

# firefox
find_and_move_app "firefox" "Firefox.app" "Firefox.app" || errored=true
find_and_move_app "firefox-beta" "Firefox.app" "Firefox Beta.app" || errored=true
find_and_move_app "firefoxdeveloperedition" "FirefoxDeveloperEdition.app" "FirefoxDeveloperEdition.app" || errored=true

# chrome
find_and_move_app "google-chrome" "Google Chrome.app" "Google Chrome.app" || errored=true
find_and_move_app "google-chrome-beta" "Google Chrome.app" "Google Chrome Beta.app" || errored=true
find_and_move_app "google-chrome-dev" "Google Chrome.app" "Google Chrome Dev.app" || errored=true

# opera
find_and_move_app "opera" "Opera.app" "Opera.app" || errored=true
find_and_move_app "opera-beta" "Opera Beta.app" "Opera Beta.app" || errored=true
find_and_move_app "opera-developer" "Opera Developer.app" "Opera Developer.app" || errored=true

### swap and rename apps with non-ASCII filenames
find_and_move_app "baiducloud" "百度云同步盘.app" "BaiduCloud.app" || errored=true
find_and_move_app "flvcd-bigrats" "硕鼠MAC.app" "BigRats.app" || errored=true

### open apps for setup
echo "${BOLD}${BLUE}open -g -a 'Touch Unlock for Mac'${RESET}" >&2
open -g -a 'Touch Unlock for Mac'

[[ $errored == false ]]
