#!/usr/bin/env zsh

errored=false

### move apps into /Applications
function find_and_move_app
{
    setopt nullglob
    paths=( /opt/homebrew-cask/Caskroom/"$1"/*/"$2" )
    [[ -n $paths ]] || { print -P "%F{red}error: no install found in /opt/homebrew-cask/Caskroom/$1%f" >&2; return 1; }
    src=${paths[-1]}
    dst=/Applications/$3
    print -P "%B%F{blue}rm -f '$dst'%f%b" >&2
    rm -f $dst || { print -P "%F{red}error: '$dst' already exists%f" >&2; return 1; }
    print -P "%B%F{blue}mv '$src' '$dst'%f%b" >&2
    mv $src $dst || { print -P "%F{red}error: failed to move into '$dst'%f" >&2; return 1; }
    print -P "%B%F{blue}ln -s '$dst' '$src'%f%b" >&2
    ln -s $dst $src
}

### apps that have to live in /Applications
find_and_move_app "chromium" "chrome-mac/Chromium.app" "Chromium.app" || errored=true
find_and_move_app "firefox" "Firefox.app" "Firefox.app" || errored=true
find_and_move_app "firefoxdeveloperedition" "FirefoxDeveloperEdition.app" "FirefoxDeveloperEdition.app" || errored=true
find_and_move_app "google-chrome" "Google Chrome.app" "Google Chrome.app" || errored=true
find_and_move_app "opera" "Opera.app" "Opera.app" || errored=true
find_and_move_app "opera-beta" "Opera Beta.app" "Opera Beta.app" || errored=true
find_and_move_app "opera-developer" "Opera Developer.app" "Opera Developer.app" || errored=true
find_and_move_app "tunnelblick" "Tunnelblick.app" "Tunnelblick.app" || errored=true

### swap and rename apps with non-ASCII filenames
find_and_move_app "baiducloud" "百度云同步盘.app" "BaiduCloud.app" || errored=true
find_and_move_app "flvcd-bigrats" "硕鼠MAC.app" "BigRats.app" || errored=true

# other
vagrant plugin install vagrant-scp vagrant-timezone

[[ $errored == false ]]
