#!/usr/bin/env zsh
here=${0:A:h}
source $here/../provision.d/messaging_helpers

print_command "cd ${(q-)here}"
cd $here || { print_error "cd failed."; exit 1; }

print_command "gem install bundler"
gem install bundler || { print_error "Failed to install bundler."; exit 1; }

print_command "bundle install --system"
bundle install --system || { print_error "'bundle install --system' failed for Gemfile ${(q-)${:-$here/Gemfile}}."; exit 1; }
