#!/usr/bin/env zsh
here=${0:A:h}
source $here/../provision.d/messaging_helpers

print_command "cd ${(q-)here}"
cd $here || { print_error "cd failed."; exit 1; }

print_command "bundle update"
bundle update || { print_error "'bundle update' failed for Gemfile ${(q-)${:-$here/Gemfile}}."; exit 1; }
