#!/usr/bin/env bash
here=$(dirname "$(realpath "$0")")

echo "${BOLD}${BLUE}cd '$here'${RESET}" >&2
cd "$here" || { echo "${RED}error: cd failed${RESET}" >&2; exit 1; }

echo "${BOLD}${BLUE}bundle update${RESET}" >&2
bundle update || { echo "${RED}error: 'bundle update' failed; Gemfile: $PWD/Gemfile${RESET}" >&2; exit 1; }
