#!/usr/bin/env zsh

function print_progress { { print -nP $'%F{green}'; print -Rn $1; print -P '%f'; } >&2 }
function print_command { { print -nP '%B%F{blue}==> '; print -Rn $1; print -P '%f%b'; } >&2 }
function print_error { { print -nP '%F{red}Error: '; print -Rn $1; print -P '%f'; } >&2 }

print_progress "Cloning cron configurations and scripts..."
repo_path="$HOME/.cron"
url="git@gitlab.com:zmwangx/cron.git"
if [[ -d $repo_path ]]; then
    print_progress "Repository '$repo_path' already exists"
else
    print_command "git clone --recursive '$url' '$repo_path'"
    git clone --recursive $url $repo_path || {
        print_error "Failed to clone repository '$url' into '$repo_path'"
        exit 1
    }
fi
[[ -e ~/.cron/crontab ]] || { print_error "Crontab '~/.cron/crontab' does not exist"; exit 1; }
print_command "crontab ~/.cron/crontab"
/usr/bin/crontab ~/.cron/crontab || { print_error "Failed to set crontab"; exit 1; }
