#!/usr/bin/env zsh

here=${0:A:h}
source $here/messaging_helpers

print_progress "Cloning cron configurations and scripts..."
repo_path="$HOME/.cron"
url="git@gitlab.com:zmwangx/cron.git"
if [[ -d $repo_path ]]; then
    print_progress "Repository '$repo_path' already exists"
else
    print_command "git clone --recursive '$url' '$repo_path'"
    git clone --recursive $url $repo_path || {
        print_error "Failed to clone repository '$url' into '$repo_path'"
        exit 1
    }
fi
[[ -e ~/.cron/crontab ]] || { print_error "Crontab '~/.cron/crontab' does not exist"; exit 1; }
print_command "crontab ~/.cron/crontab"
/usr/bin/crontab ~/.cron/crontab || { print_error "Failed to set crontab"; exit 1; }
