#!/usr/bin/env zsh

# This provisioner installs Emacs packages required in ~/.emacs.d/init.el.

here=${0:A:h}
source $here/messaging_helpers

print_command "/usr/local/bin/emacs --batch -l ~/.emacs.d/init.el"
/usr/local/bin/emacs --batch -l ~/.emacs.d/init.el
