#!/usr/bin/env zsh

# This provisioner installs Emacs packages required in ~/.emacs.d/init.el.

here=$(perl -e 'use File::Basename; use Cwd "abs_path"; print dirname(abs_path(@ARGV[0]));' -- "$0")
source $here/messaging_helpers

print_command "/usr/local/bin/emacs --batch -l ~/.emacs.d/init.el"
/usr/local/bin/emacs --batch -l ~/.emacs.d/init.el
