#!/usr/bin/env zsh

here=$(perl -e 'use File::Basename; use Cwd "abs_path"; print dirname(abs_path(@ARGV[0]));' -- "$0")
source $here/messaging_helpers

# suppress last login message upon login
print_command "touch ~/.hushlogin"
touch ~/.hushlogin
