#!/usr/bin/env zsh

here=$(perl -e 'use File::Basename; use Cwd "abs_path"; print dirname(abs_path(@ARGV[0]));' -- "$0")
source $here/messaging_helpers

if [[ -e $HOME/.rvm/scripts/rvm ]]; then
    print_progress "RVM already installed in $HOME/.rvm"
else
    print_progress "Installing RVM from get.rvm.io..."
    print_command "gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 || {
        print_error "Failed to download GPG key"
        exit 1
    }
    install_script_url='https://get.rvm.io'
    install_script_tmp_path=$(mktemp) || {
        print_error "Failed to generate temporary path for RVM install script with mktemp"
        exit 1
    }
    trap "rm -f ${(qq)install_script_tmp_path}" EXIT
    print_command "curl -fsSL $install_script_url >${(qq)install_script_tmp_path}"
    curl -fsSL $install_script_url >$install_script_tmp_path || {
        print_error "Failed to curl RVM install script from $install_script_url"
        exit 1
    }
    print_command "bash -- ${(qq)install_script_tmp_path} --user-install --ignore-dotfiles --ruby stable"
    bash -- $install_script_tmp_path --user-install --ignore-dotfiles --ruby stable </dev/null || {
        print_error "Failed to install RVM"
        exit 1
    }
fi
