#!/usr/bin/env zsh

# This script checks out helper scripts at ~/dev/scripts.

here=${0:A:h}
source $here/messaging_helpers

if [[ -d ~/dev/scripts ]]; then
    print_progress "'~/dev/scripts' already exists"
else
    print_command "mkdir -p ~/dev/scripts"
    mkdir -p ~/dev/scripts
    print_command "git clone --recursive git@gitlab.com:zmwangx/scripts.git ~/dev/scripts"
    git clone --recursive git@gitlab.com:zmwangx/scripts.git ~/dev/scripts || {
        print_error "Failed to clone repository 'git@gitlab.com:zmwangx/scripts.git' to '~/dev/scripts'"
        exit 1
    }
fi
