# -*- mode: sh; -*-

# if local override exists, source the override instead
[[ -e ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zlogin_override ]] && { source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zlogin_override && return; }

# source per-host additions
[[ -e ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/perhostlogin ]] && source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/perhostlogin

true
