# -*- mode: sh; -*-

# if local override exists, source the override instead
[[ -e ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zshenv_override ]] && { source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zshenv_override && return; }

# get global env
source ${XDG_CONFIG_HOME:-$HOME/.config}/env

# source per-host additions
[[ -e ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/perhostenv ]] && source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/perhostenv

# remove dupes in paths
typeset -gU cdpath fpath mailpath path

# skip global init files other than /etc/zshenv entirely
unsetopt globalrcs
