# -*- mode: sh; -*-

# path for zcompdump
ZCOMPDUMP=${XDG_DATA_HOME:-$HOME/.local/share}/zsh/compdump

# prezto
zstyle ':prezto:*:*' color 'yes'
zstyle ':prezto:environment:termcap' color 'no' # disable coloring of less, which looks horrible
zstyle ':prezto:module:editor' key-bindings 'emacs'
zstyle ':prezto:module:prompt' theme 'zmwangx'
zstyle ':prezto:load' pmodule \
       environment editor history directory utility colors spectrum git completion prompt \
       archive bd homebrew iterm2 osx diskutil python ruby \
       local
source ~/.zprezto/init.zsh

# source extras
for script in ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/extras/*.zsh(N); do source $script; done

# source per-host overrides
[[ -e ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/perhostrc ]] && source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/perhostrc

# remove dupes in paths
typeset -gU cdpath fpath mailpath path
