# -*- mode: sh; -*-

# if local override exists, source the override instead
[[ -e ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zshrc_override ]] && { source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/zshrc_override && return; }

# path for zcompdump
ZCOMPDUMP=${XDG_DATA_HOME:-$HOME/.local/share}/zsh/compdump

# prezto
zstyle ':prezto:*:*' color 'yes'
zstyle ':prezto:environment:termcap' color 'no' # disable coloring of less, which looks horrible
zstyle ':prezto:module:editor' key-bindings 'emacs'
zstyle ':prezto:module:prompt' theme 'zmwangx'
zstyle ':prezto:load' pmodule \
       environment editor history directory utility colors git completion prompt \
       archive bd fasd homebrew iterm2 osx diskutil calendar python \
       local
source ~/.zprezto/init.zsh

# source extras
for script in ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/extras/*.zsh(N); do source $script; done

# source per-host additions
[[ -e ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/perhostrc ]] && source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/perhostrc

# remove dupes in paths
typeset -gU cdpath fpath mailpath path

# unset stupid variables set in zshenv
unset skip_global_compinit
